package com.aeza.chat;

import com.aeza.parse.R;

import java.util.Random;

class AvatarPicker {

    public static int getRandomAvatar() {
        int ran = new Random().nextInt(73 - 1) + 1;
        switch (ran) {
            case 1:
                return R.drawable.avatar1;
            case 2:
                return R.drawable.avatar2;
            case 3:
                return R.drawable.avatar3;
            case 4:
                return R.drawable.avatar4;
            case 5:
                return R.drawable.avatar5;
            case 6:
                return R.drawable.avatar6;
            case 7:
                return R.drawable.avatar7;
            case 8:
                return R.drawable.avatar8;
            case 9:
                return R.drawable.avatar9;
            case 10:
                return R.drawable.avatar10;
            case 11:
                return R.drawable.avatar11;
            case 12:
                return R.drawable.avatar12;
            case 13:
                return R.drawable.avatar13;
            case 14:
                return R.drawable.avatar14;
            case 15:
                return R.drawable.avatar15;
            case 16:
                return R.drawable.avatar16;
            case 17:
                return R.drawable.avatar17;
            case 18:
                return R.drawable.avatar18;
            case 19:
                return R.drawable.avatar19;
            case 20:
                return R.drawable.avatar20;
            case 21:
                return R.drawable.avatar21;
            case 22:
                return R.drawable.avatar22;
            case 23:
                return R.drawable.avatar23;
            case 24:
                return R.drawable.avatar24;
            case 25:
                return R.drawable.avatar25;
            case 26:
                return R.drawable.avatar26;
            case 27:
                return R.drawable.avatar27;
            case 28:
                return R.drawable.avatar28;
            case 29:
                return R.drawable.avatar29;
            case 30:
                return R.drawable.avatar30;
            case 31:
                return R.drawable.avatar31;
            case 32:
                return R.drawable.avatar32;
            case 33:
                return R.drawable.avatar33;
            case 34:
                return R.drawable.avatar34;
            case 35:
                return R.drawable.avatar35;
            case 36:
                return R.drawable.avatar36;
            case 37:
                return R.drawable.avatar37;
            case 38:
                return R.drawable.avatar38;
            case 39:
                return R.drawable.avatar39;
            case 40:
                return R.drawable.avatar40;
            case 41:
                return R.drawable.avatar41;
            case 42:
                return R.drawable.avatar42;
            case 43:
                return R.drawable.avatar43;
            case 44:
                return R.drawable.avatar44;
            case 45:
                return R.drawable.avatar45;
            case 46:
                return R.drawable.avatar46;
            case 47:
                return R.drawable.avatar47;
            case 48:
                return R.drawable.avatar48;
            case 49:
                return R.drawable.avatar49;
            case 50:
                return R.drawable.avatar50;
            case 51:
                return R.drawable.avatar51;
            case 52:
                return R.drawable.avatar52;
            case 53:
                return R.drawable.avatar53;
            case 54:
                return R.drawable.avatar54;
            case 55:
                return R.drawable.avatar55;
            case 56:
                return R.drawable.avatar56;
            case 57:
                return R.drawable.avatar57;
            case 58:
                return R.drawable.avatar58;
            case 59:
                return R.drawable.avatar59;
            case 60:
                return R.drawable.avatar60;
            case 61:
                return R.drawable.avatar61;
            case 62:
                return R.drawable.avatar62;
            case 63:
                return R.drawable.avatar63;
            case 64:
                return R.drawable.avatar64;
            case 65:
                return R.drawable.avatar65;
            case 66:
                return R.drawable.avatar66;
            case 67:
                return R.drawable.avatar67;
            case 68:
                return R.drawable.avatar68;
            case 69:
                return R.drawable.avatar69;
            case 70:
                return R.drawable.avatar70;
            case 71:
                return R.drawable.avatar71;
            case 72:
                return R.drawable.avatar72;
            default:
                return 0;
        }
    }
}
